bot:
  symbol: 'BTCUSDT'
  interval: '1m'
  start_str: '1 day ago UTC'
exchange:
  name: 'binance_testnet'
risk_management:
  stop_loss: 0.1
  max_drawdown: 0.2
capital_allocation:
  max_capital: 1000
